[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adapters"
version = "0.1.0"
description = "Adapters between OTM and external formats (Threat Dragon, Threagile)"
requires-python = ">=3.10"
dependencies = [
  "otm-model>=0.1.0",
  "pydantic>=2",
]

[tool.setuptools.packages.find]
where = ["src"]

