version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies", "security"]
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/apps/langflow-ui-extensions"
    schedule:
      interval: weekly
    labels: ["dependencies"]
    open-pull-requests-limit: 5
    allow:
      - dependency-type: direct
    ignore: []
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
    open-pull-requests-limit: 5
